services:
  - type: web
    name: jjapipj
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y wget curl gnupg2 ca-certificates lsb-release
      echo "deb http://deb.debian.org/debian buster-backports main" | tee -a /etc/apt/sources.list
      apt-get update
      apt-get install -y firefox-esr
      wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
      tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
      mv geckodriver /usr/local/bin/
      chmod +x /usr/local/bin/geckodriver
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api-casos:app --host 0.0.0.0 --port $PORT
